apiVersion: v1  # Versión de la API
kind: PersistentVolumeClaim  # Tipo de recurso
metadata:
  name: postgres-pvc  # Nombre del PVC para PostgreSQL
spec:
  accessModes:
    - ReadWriteOnce  # Modo de acceso: lectura/escritura por un nodo
  resources:
    requests:
      storage: 300Mi  # Solicitud de almacenamiento: 300 MiB
---
apiVersion: v1  # Versión de la API
kind: PersistentVolumeClaim  # Tipo de recurso
metadata:
  name: static-pvc  # Nombre del PVC para archivos estáticos
spec:
  accessModes:
    - ReadWriteOnce # Modo de acceso: lectura/escritura por un nodo
  resources:
    requests:
      storage: 100Mi  # Solicitud de almacenamiento: 100 MiB