# Generated by Django 5.1.1 on 2024-09-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='image',
            field=models.TextField(),
        ),
    ]
