# Generated by Django 5.1.1 on 2024-09-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_imagerequest_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerequest',
            name='image',
            field=models.CharField(),
        ),
    ]
